import { useState } from "react";
import { Link } from "@tanstack/react-router";
import { useQuery, useMutation, useQueryClient } from "@tanstack/react-query";
import { Trash2, Pencil } from "lucide-react";
import {
  getSummary,
  getEntities,
  getTags,
  getRelated,
  listComments,
  createComment,
  updateComment,
  deleteComment,
  listAnnotations,
  createAnnotation,
  deleteAnnotation,
} from "@/api/documents";
import { Badge } from "@/components/primitives/Badge";
import { Button } from "@/components/primitives/Button";
import { EmptyState } from "@/components/primitives/EmptyState";
import { Tabs } from "@/components/primitives/Tabs";
import { useToast } from "@/components/primitives/ToastContext";
import styles from "./DetailsPanel.module.css";

const TABS = [
  { id: "summary", label: "Summary" },
  { id: "entities", label: "Entities" },
  { id: "tags", label: "Tags" },
  { id: "related", label: "Related" },
  { id: "annotations", label: "Annotations" },
  { id: "comments", label: "Comments" },
];

interface DetailsPanelProps {
  docId: string;
}

export function DetailsPanel({ docId }: DetailsPanelProps) {
  const [activeTab, setActiveTab] = useState("summary");

  return (
    <div className={styles.panel}>
      <Tabs
        tabs={TABS}
        active={activeTab}
        onChange={setActiveTab}
        className={styles.tabs}
      />
      <div className={styles.content}>
        {activeTab === "summary" && <SummaryTab docId={docId} />}
        {activeTab === "entities" && <EntitiesTab docId={docId} />}
        {activeTab === "tags" && <TagsTab docId={docId} />}
        {activeTab === "related" && <RelatedTab docId={docId} />}
        {activeTab === "annotations" && <AnnotationsTab docId={docId} />}
        {activeTab === "comments" && <CommentsTab docId={docId} />}
      </div>
    </div>
  );
}

function SummaryTab({ docId }: { docId: string }) {
  const { data, isLoading, isError } = useQuery({
    queryKey: ["doc-summary", docId],
    queryFn: () => getSummary(docId),
    retry: false,
  });

  if (isLoading) return <p className={styles.muted}>Loading…</p>;
  if (isError || !data)
    return (
      <EmptyState
        title="No summary"
        body="AI summary not yet available for this document."
      />
    );

  return (
    <div className={styles.summaryBlock}>
      <p className={styles.summaryText}>{data.summary}</p>
      <p className={styles.meta}>
        Generated by {data.model} ·{" "}
        {new Date(data.updated_at).toLocaleDateString()}
      </p>
    </div>
  );
}

function EntitiesTab({ docId }: { docId: string }) {
  const { data, isLoading, isError } = useQuery({
    queryKey: ["doc-entities", docId],
    queryFn: () => getEntities(docId),
    retry: false,
  });

  if (isLoading) return <p className={styles.muted}>Loading…</p>;
  if (isError)
    return (
      <EmptyState
        title="Failed to load entities"
        body="Could not reach the server."
      />
    );
  if (!data?.entities.length)
    return (
      <EmptyState
        title="No entities"
        body="No entities extracted for this document."
      />
    );

  return (
    <ul className={styles.entityList}>
      {data.entities.map((e, i) => (
        <li key={i} className={styles.entityRow}>
          <span className={styles.entityLabel}>{e.label}</span>
          <Badge variant="neutral">{e.type}</Badge>
          <span className={styles.entityCount}>×{e.count}</span>
        </li>
      ))}
    </ul>
  );
}

function TagsTab({ docId }: { docId: string }) {
  const { data, isLoading, isError } = useQuery({
    queryKey: ["doc-tags", docId],
    queryFn: () => getTags(docId),
    retry: false,
  });

  if (isLoading) return <p className={styles.muted}>Loading…</p>;
  if (isError)
    return (
      <EmptyState
        title="Failed to load tags"
        body="Could not reach the server."
      />
    );
  if (!data?.tags.length)
    return (
      <EmptyState title="No tags" body="No tags assigned to this document." />
    );

  return (
    <div className={styles.tagCloud}>
      {data.tags.map((tag) => (
        <Badge key={tag} variant="tag">
          {tag}
        </Badge>
      ))}
    </div>
  );
}

function RelatedTab({ docId }: { docId: string }) {
  const { data, isLoading, isError } = useQuery({
    queryKey: ["doc-related", docId],
    queryFn: () => getRelated(docId),
    retry: false,
  });

  if (isLoading) return <p className={styles.muted}>Loading…</p>;
  if (isError)
    return (
      <EmptyState
        title="Failed to load related documents"
        body="Could not reach the server."
      />
    );
  if (!data?.related.length)
    return (
      <EmptyState
        title="No related documents"
        body="No related documents found."
      />
    );

  return (
    <ul className={styles.relatedList}>
      {data.related.map((doc) => (
        <li key={doc.document_id}>
          <Link
            to="/doc/$docId"
            params={{ docId: doc.document_id }}
            className={styles.relatedLink}
          >
            <span className={styles.relatedTitle}>{doc.title}</span>
            <Badge variant="source">{doc.source_label}</Badge>
          </Link>
        </li>
      ))}
    </ul>
  );
}

function AnnotationsTab({ docId }: { docId: string }) {
  const [newText, setNewText] = useState("");
  const [isPrivate, setIsPrivate] = useState(true);
  const { show: showToast } = useToast();
  const qc = useQueryClient();

  const { data, isLoading, isError } = useQuery({
    queryKey: ["doc-annotations", docId],
    queryFn: () => listAnnotations(docId),
  });

  const invalidate = () =>
    void qc.invalidateQueries({ queryKey: ["doc-annotations", docId] });

  const addMut = useMutation({
    mutationFn: () =>
      createAnnotation(docId, {
        text: newText.trim(),
        position: null,
        is_private: isPrivate,
      }),
    onSuccess: () => {
      setNewText("");
      invalidate();
    },
    onError: () => showToast("error", "Failed to add annotation."),
  });

  const deleteMut = useMutation({
    mutationFn: (id: string) => deleteAnnotation(id),
    onSuccess: invalidate,
    onError: () => showToast("error", "Failed to delete annotation."),
  });

  const annotations = data?.annotations ?? [];

  return (
    <div className={styles.commentsSection}>
      {isLoading && <p className={styles.muted}>Loading…</p>}
      {isError && (
        <EmptyState
          title="Failed to load annotations"
          body="Could not reach the server."
        />
      )}
      {!isLoading && !isError && annotations.length === 0 && (
        <p className={styles.muted}>No annotations yet.</p>
      )}
      <ul className={styles.commentList}>
        {annotations.map((a) => (
          <li key={a.id} className={styles.comment}>
            <div className={styles.commentMeta}>
              <Badge variant={a.is_private ? "neutral" : "source"}>
                {a.is_private ? "Private" : "Shared"}
              </Badge>
              <span className={styles.commentDate}>
                {new Date(a.created_at).toLocaleDateString()}
              </span>
              {a.can_modify && (
                <button
                  className={styles.iconAction}
                  aria-label="Delete annotation"
                  onClick={() => deleteMut.mutate(a.id)}
                >
                  <Trash2 size={13} />
                </button>
              )}
            </div>
            <p className={styles.commentBody}>{a.text}</p>
          </li>
        ))}
      </ul>
      <div className={styles.addComment}>
        <input
          className={styles.inlineInput}
          value={newText}
          onChange={(e) => setNewText(e.target.value)}
          placeholder="Add an annotation…"
          aria-label="New annotation"
        />
        <label className={styles.visibilityLabel}>
          <input
            type="checkbox"
            checked={isPrivate}
            onChange={(e) => setIsPrivate(e.target.checked)}
          />
          Private
        </label>
        <Button
          size="sm"
          onClick={() => addMut.mutate()}
          disabled={!newText.trim() || addMut.isPending}
        >
          Add
        </Button>
      </div>
    </div>
  );
}

function CommentsTab({ docId }: { docId: string }) {
  const [newBody, setNewBody] = useState("");
  const [editId, setEditId] = useState<string | null>(null);
  const [editBody, setEditBody] = useState("");
  const { show: showToast } = useToast();
  const qc = useQueryClient();

  const { data, isLoading } = useQuery({
    queryKey: ["doc-comments", docId],
    queryFn: () => listComments(docId),
  });

  const invalidate = () =>
    void qc.invalidateQueries({ queryKey: ["doc-comments", docId] });

  const addMut = useMutation({
    mutationFn: () => createComment(docId, newBody.trim()),
    onSuccess: () => {
      setNewBody("");
      invalidate();
    },
    onError: () => showToast("error", "Failed to post comment."),
  });

  const editMut = useMutation({
    mutationFn: () => updateComment(docId, editId!, editBody.trim()),
    onSuccess: () => {
      setEditId(null);
      invalidate();
    },
    onError: () => showToast("error", "Failed to update comment."),
  });

  const deleteMut = useMutation({
    mutationFn: (id: string) => deleteComment(docId, id),
    onSuccess: invalidate,
    onError: () => showToast("error", "Failed to delete comment."),
  });

  const activeComments = data?.comments.filter((c) => !c.deleted_at) ?? [];

  return (
    <div className={styles.commentsSection}>
      {isLoading && <p className={styles.muted}>Loading…</p>}
      {!isLoading && activeComments.length === 0 && (
        <p className={styles.muted}>No comments yet.</p>
      )}
      <ul className={styles.commentList}>
        {activeComments.map((c) => (
          <li key={c.id} className={styles.comment}>
            {editId === c.id ? (
              <div className={styles.commentEditRow}>
                <input
                  className={styles.inlineInput}
                  value={editBody}
                  onChange={(e) => setEditBody(e.target.value)}
                  aria-label="Edit comment"
                />
                <Button
                  size="sm"
                  onClick={() => editMut.mutate()}
                  disabled={!editBody.trim() || editMut.isPending}
                >
                  Save
                </Button>
                <Button
                  size="sm"
                  variant="secondary"
                  onClick={() => setEditId(null)}
                >
                  Cancel
                </Button>
              </div>
            ) : (
              <>
                <div className={styles.commentMeta}>
                  <span className={styles.commentAuthor}>
                    {c.author_display_name}
                  </span>
                  <span className={styles.commentDate}>
                    {new Date(c.created_at).toLocaleDateString()}
                  </span>
                  {c.can_edit && (
                    <button
                      className={styles.iconAction}
                      aria-label="Edit comment"
                      onClick={() => {
                        setEditId(c.id);
                        setEditBody(c.body);
                      }}
                    >
                      <Pencil size={13} />
                    </button>
                  )}
                  {c.can_delete && (
                    <button
                      className={styles.iconAction}
                      aria-label="Delete comment"
                      onClick={() => deleteMut.mutate(c.id)}
                    >
                      <Trash2 size={13} />
                    </button>
                  )}
                </div>
                <p className={styles.commentBody}>{c.body}</p>
              </>
            )}
          </li>
        ))}
      </ul>
      <div className={styles.addComment}>
        <input
          className={styles.inlineInput}
          value={newBody}
          onChange={(e) => setNewBody(e.target.value)}
          placeholder="Add a comment…"
          aria-label="New comment"
        />
        <Button
          size="sm"
          onClick={() => addMut.mutate()}
          disabled={!newBody.trim() || addMut.isPending}
        >
          Post
        </Button>
      </div>
    </div>
  );
}
