import { useState } from "react";
import { Link } from "@tanstack/react-router";
import { useQuery, useMutation, useQueryClient } from "@tanstack/react-query";
import { Trash2, Pencil } from "lucide-react";
import {
  getSummary, getEntities, getTags, getRelated,
  listComments, createComment, updateComment, deleteComment,
  listAnnotations, createAnnotation, deleteAnnotation,
} from "@/api/documents";
import { Badge } from "@/components/primitives/Badge";
import { Button } from "@/components/primitives/Button";
import { EmptyState } from "@/components/primitives/EmptyState";
import { Tabs } from "@/components/primitives/Tabs";
import { useToast } from "@/components/primitives/ToastContext";
import { QAPanel } from "@/features/qa/QAPanel";
import type { InsightPaneTab } from "./insightPaneTabs";
import styles from "./InsightPane.module.css";

const TABS: { id: InsightPaneTab; label: string }[] = [
  { id: "summary", label: "Summary" },
  { id: "qa", label: "Q&A" },
  { id: "related", label: "Related" },
  { id: "annotations", label: "Annotations" },
  { id: "comments", label: "Comments" },
  { id: "subscriptions", label: "Subscriptions" },
];

interface InsightPaneProps {
  docId: string;
}

export function InsightPane({ docId }: InsightPaneProps) {
  const [activeTab, setActiveTab] = useState<InsightPaneTab>("summary");

  return (
    <div className={styles.pane}>
      <Tabs
        tabs={TABS}
        active={activeTab}
        onChange={(id) => setActiveTab(id as InsightPaneTab)}
        className={styles.tabs}
      />
      <div className={styles.content}>
        {activeTab === "summary" && <SummaryTab docId={docId} />}
        {activeTab === "qa" && <QAPanel />}
        {activeTab === "related" && <RelatedTab docId={docId} />}
        {activeTab === "annotations" && <AnnotationsTab docId={docId} />}
        {activeTab === "comments" && <CommentsTab docId={docId} />}
        {activeTab === "subscriptions" && <SubscriptionsStub />}
      </div>
    </div>
  );
}

function SummaryTab({ docId }: { docId: string }) {
  const { data, isLoading, isError } = useQuery({
    queryKey: ["doc-summary", docId],
    queryFn: () => getSummary(docId),
    retry: false,
  });

  if (isLoading) return <p className={styles.muted}>Loading…</p>;
  if (isError) return <EmptyState title="Failed to load summary" body="Could not reach the server." />;
  if (!data) return <EmptyState title="No summary" body="AI summary not yet available for this document." />;

  return (
    <div className={styles.summaryBlock}>
      <p className={styles.summaryText}>{data.summary}</p>
      <p className={styles.meta}>Generated by {data.model} · {new Date(data.updated_at).toLocaleDateString()}</p>
      <EntitiesSection docId={docId} />
      <TagsSection docId={docId} />
    </div>
  );
}

function EntitiesSection({ docId }: { docId: string }) {
  const { data, isLoading, isError } = useQuery({
    queryKey: ["doc-entities", docId],
    queryFn: () => getEntities(docId),
    retry: false,
  });

  if (isLoading || isError || !data?.entities.length) return null;

  return (
    <div className={styles.section}>
      <h3 className={styles.sectionHeading}>Entities</h3>
      <ul className={styles.entityList}>
        {data.entities.map((e) => (
          <li key={`${e.label}-${e.type}`} className={styles.entityRow}>
            <span className={styles.entityLabel}>{e.label}</span>
            <Badge variant="neutral">{e.type}</Badge>
            <span className={styles.entityCount}>×{e.count}</span>
          </li>
        ))}
      </ul>
    </div>
  );
}

function TagsSection({ docId }: { docId: string }) {
  const { data, isLoading, isError } = useQuery({
    queryKey: ["doc-tags", docId],
    queryFn: () => getTags(docId),
    retry: false,
  });

  if (isLoading || isError || !data?.tags.length) return null;

  return (
    <div className={styles.section}>
      <h3 className={styles.sectionHeading}>Tags</h3>
      <div className={styles.tagCloud}>
        {data.tags.map((tag) => (
          <Badge key={tag} variant="tag">{tag}</Badge>
        ))}
      </div>
    </div>
  );
}

function RelatedTab({ docId }: { docId: string }) {
  const { data, isLoading, isError } = useQuery({
    queryKey: ["doc-related", docId],
    queryFn: () => getRelated(docId),
    retry: false,
  });

  if (isLoading) return <p className={styles.muted}>Loading…</p>;
  if (isError) return <EmptyState title="Failed to load related documents" body="Could not reach the server." />;
  if (!data?.related.length) return <EmptyState title="No related documents" body="No related documents found." />;

  return (
    <ul className={styles.relatedList}>
      {data.related.map((doc) => (
        <li key={doc.doc_id}>
          <Link to="/doc/$docId" params={{ docId: doc.doc_id }} className={styles.relatedLink}>
            <span className={styles.relatedTitle}>{doc.title}</span>
            <Badge variant="source">{doc.source_label}</Badge>
          </Link>
        </li>
      ))}
    </ul>
  );
}

const PLACEHOLDER_POSITION = { mode: "text-range" as const, start_char: 0, end_char: 0 };

function AnnotationsTab({ docId }: { docId: string }) {
  const [newText, setNewText] = useState("");
  const [isPrivate, setIsPrivate] = useState(true);
  const { show: showToast } = useToast();
  const qc = useQueryClient();

  const { data, isLoading, isError } = useQuery({
    queryKey: ["doc-annotations", docId],
    queryFn: () => listAnnotations(docId),
  });

  const invalidate = () => void qc.invalidateQueries({ queryKey: ["doc-annotations", docId] });

  const addMut = useMutation({
    mutationFn: () => createAnnotation(docId, { text: newText.trim(), position: PLACEHOLDER_POSITION, is_private: isPrivate }),
    onSuccess: () => { setNewText(""); invalidate(); },
    onError: () => showToast("error", "Failed to add annotation."),
  });

  const deleteMut = useMutation({
    mutationFn: (id: string) => deleteAnnotation(id),
    onSuccess: invalidate,
    onError: () => showToast("error", "Failed to delete annotation."),
  });

  const annotations = data?.annotations ?? [];

  return (
    <div className={styles.commentsSection}>
      {isLoading && <p className={styles.muted}>Loading…</p>}
      {isError && <EmptyState title="Failed to load annotations" body="Could not reach the server." />}
      {!isLoading && !isError && annotations.length === 0 && (
        <p className={styles.muted}>No annotations yet.</p>
      )}
      <ul className={styles.commentList}>
        {annotations.map((a) => (
          <li key={a.id} className={styles.comment}>
            <div className={styles.commentMeta}>
              <Badge variant={a.is_private ? "neutral" : "source"}>
                {a.is_private ? "Private note" : "Shared with readers"}
              </Badge>
              <span className={styles.commentDate}>{new Date(a.created_at).toLocaleDateString()}</span>
              {a.can_modify && (
                <button className={styles.iconAction} aria-label="Delete annotation" onClick={() => deleteMut.mutate(a.id)}>
                  <Trash2 size={13} />
                </button>
              )}
            </div>
            <p className={styles.commentBody}>{a.text}</p>
          </li>
        ))}
      </ul>
      <div className={styles.addComment}>
        <input
          className={styles.inlineInput}
          value={newText}
          onChange={(e) => setNewText(e.target.value)}
          placeholder="Add an annotation…"
          aria-label="New annotation"
        />
        <label className={styles.visibilityLabel}>
          <input type="checkbox" checked={isPrivate} onChange={(e) => setIsPrivate(e.target.checked)} />
          Private
        </label>
        <Button size="sm" onClick={() => addMut.mutate()} disabled={!newText.trim() || addMut.isPending}>
          Add
        </Button>
      </div>
    </div>
  );
}

function CommentsTab({ docId }: { docId: string }) {
  const [newBody, setNewBody] = useState("");
  const [editId, setEditId] = useState<string | null>(null);
  const [editBody, setEditBody] = useState("");
  const { show: showToast } = useToast();
  const qc = useQueryClient();

  const { data, isLoading } = useQuery({
    queryKey: ["doc-comments", docId],
    queryFn: () => listComments(docId),
  });

  const invalidate = () => void qc.invalidateQueries({ queryKey: ["doc-comments", docId] });

  const addMut = useMutation({
    mutationFn: () => createComment(docId, newBody.trim()),
    onSuccess: () => { setNewBody(""); invalidate(); },
    onError: () => showToast("error", "Failed to post comment."),
  });

  const editMut = useMutation({
    mutationFn: () => updateComment(docId, editId!, editBody.trim()),
    onSuccess: () => { setEditId(null); invalidate(); },
    onError: () => showToast("error", "Failed to update comment."),
  });

  const deleteMut = useMutation({
    mutationFn: (id: string) => deleteComment(docId, id),
    onSuccess: invalidate,
    onError: () => showToast("error", "Failed to delete comment."),
  });

  const activeComments = data?.comments.filter((c) => !c.deleted_at) ?? [];

  return (
    <div className={styles.commentsSection}>
      {isLoading && <p className={styles.muted}>Loading…</p>}
      {!isLoading && activeComments.length === 0 && <p className={styles.muted}>No comments yet.</p>}
      <ul className={styles.commentList}>
        {activeComments.map((c) => (
          <li key={c.id} className={styles.comment}>
            {editId === c.id ? (
              <div className={styles.commentEditRow}>
                <input className={styles.inlineInput} value={editBody} onChange={(e) => setEditBody(e.target.value)} aria-label="Edit comment" />
                <Button size="sm" onClick={() => editMut.mutate()} disabled={!editBody.trim() || editMut.isPending}>Save</Button>
                <Button size="sm" variant="secondary" onClick={() => setEditId(null)}>Cancel</Button>
              </div>
            ) : (
              <>
                <div className={styles.commentMeta}>
                  <span className={styles.commentAuthor}>{c.author_display_name}</span>
                  <span className={styles.commentDate}>{new Date(c.created_at).toLocaleDateString()}</span>
                  {c.can_edit && (
                    <button className={styles.iconAction} aria-label="Edit comment" onClick={() => { setEditId(c.id); setEditBody(c.body); }}>
                      <Pencil size={13} />
                    </button>
                  )}
                  {c.can_delete && (
                    <button className={styles.iconAction} aria-label="Delete comment" onClick={() => deleteMut.mutate(c.id)}>
                      <Trash2 size={13} />
                    </button>
                  )}
                </div>
                <p className={styles.commentBody}>{c.body}</p>
              </>
            )}
          </li>
        ))}
      </ul>
      <div className={styles.addComment}>
        <input
          className={styles.inlineInput}
          value={newBody}
          onChange={(e) => setNewBody(e.target.value)}
          placeholder="Add a comment…"
          aria-label="New comment"
        />
        <Button size="sm" onClick={() => addMut.mutate()} disabled={!newBody.trim() || addMut.isPending}>Post</Button>
      </div>
    </div>
  );
}

function SubscriptionsStub() {
  return (
    <EmptyState
      title="Subscriptions"
      body="Subscribe to alerts for this document. Coming in Phase 08e."
    />
  );
}
