import { describe, it, expect, vi } from "vitest";
import { screen } from "@testing-library/react";
import { render } from "@/test/render";
import { AnswerPanel } from "./AnswerPanel";

vi.mock("@tanstack/react-router", () => ({
  Link: ({ children, to }: { children: React.ReactNode; to: string }) => (
    <a href={to}>{children}</a>
  ),
}));

const mockResult = {
  question: "What is vendor risk?",
  answer: "Vendor risk is the potential exposure from third-party vendors.",
  citations: [
    {
      documantions_id: "doc-1",
      doc_title: "Vendor Policy",
      chunk_text: "Vendor risk refers to…",
      score: 0.9,
    },
  ],
  model: "ollama/mistral",
};

describe("AnswerPanel", () => {
  it("renders answer text", () => {
    render(<AnswerPanel result={mockResult} />);
    expect(
      screen.getByText(
        "Vendor risk is the potential exposure from third-party vendors."
      )
    ).toBeInTheDocument();
  });

  it("renders citation title", () => {
    render(<AnswerPanel result={mockResult} />);
    expect(
      screen.getByRole("link", { name: "Vendor Policy" })
    ).toBeInTheDocument();
  });

  it("renders model note", () => {
    render(<AnswerPanel result={mockResult} />);
    expect(screen.getByText("Generated by ollama/mistral")).toBeInTheDocument();
  });

  it("renders grounding note", () => {
    render(<AnswerPanel result={mockResult} />);
    expect(screen.getByText(/based only on documents/i)).toBeInTheDocument();
  });

  it("does not render model note when empty", () => {
    render(<AnswerPanel result={{ ...mockResult, model: "" }} />);
    expect(screen.queryByText(/Generated by/)).not.toBeInTheDocument();
  });
});
