import { useState } from "react";
import { Link } from "@tanstack/react-router";
import { useMutation } from "@tanstack/react-query";
import { askQuestion, type QAResponse } from "@/api/qa";
import { Button } from "@/components/primitives/Button";
import { EmptyState } from "@/components/primitives/EmptyState";
import { useToast } from "@/components/primitives/ToastContext";
import styles from "./QAPage.module.css";

export function QAPage() {
  const [question, setQuestion] = useState("");
  const [result, setResult] = useState<QAResponse | null>(null);
  const [hasError, setHasError] = useState(false);
  const { show: showToast } = useToast();

  const mutation = useMutation({
    mutationFn: () => askQuestion(question.trim()),
    onSuccess: (data) => { setHasError(false); setResult(data); },
    onError: () => { setHasError(true); showToast("error", "Q&A request failed. Check that the backend is reachable."); },
  });

  function handleSubmit(e: React.FormEvent) {
    e.preventDefault();
    if (question.trim()) mutation.mutate();
  }

  return (
    <div className={styles.page}>
      <header className={styles.header}>
        <h1 className={styles.title}>Q&amp;A</h1>
      </header>

      <div className={styles.body}>
        <form className={styles.form} onSubmit={handleSubmit} role="search" aria-label="Ask a question">
          <textarea
            className={styles.questionInput}
            value={question}
            onChange={(e) => setQuestion(e.target.value)}
            placeholder="Ask a question about your documents…"
            aria-label="Question"
            rows={3}
            onKeyDown={(e) => {
              if (e.key === "Enter" && !e.shiftKey) { e.preventDefault(); if (question.trim()) mutation.mutate(); }
            }}
          />
          <Button type="submit" disabled={!question.trim() || mutation.isPending} loading={mutation.isPending}>
            Ask
          </Button>
        </form>

        {hasError && !result && (
          <EmptyState
            title="Request failed"
            body="The Q&A service is not reachable. Check the server and try again."
          />
        )}

        {!result && !hasError && !mutation.isPending && (
          <EmptyState
            title="Ask anything"
            body="Type a question and press Ask. Answers are grounded in your accessible documents."
          />
        )}

        {result && (
          <div className={styles.result}>
            <div className={styles.questionEcho}>{result.question}</div>
            <div className={styles.answer}>{result.answer}</div>

            {result.citations.length > 0 && (
              <div className={styles.citations}>
                <h2 className={styles.citationsHeading}>Sources</h2>
                <ul className={styles.citationList}>
                  {result.citations.map((c, i) => (
                    <li key={i} className={styles.citation}>
                      <Link to="/doc/$docId" params={{ docId: c.doc_id }} className={styles.citationLink}>
                        {c.doc_title || c.doc_id}
                      </Link>
                      <p className={styles.citationChunk}>{c.chunk_text}</p>
                    </li>
                  ))}
                </ul>
              </div>
            )}

            {result.model && (
              <p className={styles.modelNote}>Generated by {result.model}</p>
            )}
          </div>
        )}
      </div>
    </div>
  );
}
