apiVersion: 1

datasources:
  - name: Neverland Prometheus
    type: prometheus
    uid: neverland-prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: false
